# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0fe237a6699ad53873b09c38af114960c5ce037ee8b08682c557081cbbf513f2ac338e7b27fd88696ab203753d7aa75b34aa07963fcdb6a9a964caf69094b874

test:
  secret_key_base: ffeb29c310b468e42828afd65f5e5cb7dc0ac735c41a6ee92a7f8e8f00c469cb0c4f18270fe09fb3d4c5c86c236ccc249a2817e5f6fb670cd4d8a54d4551ef01

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
